### ISSUE TITLE
Notification Framework Performance Updates

### ISSUE THREAD

**Issue by sf2ne** [open-horizon/exchange-api#295]
This is part of Epic 253
- [x] change resourcechanges table lastUpdated to `timestamptz`
- [x] add index for lastUpdated to the table schema
- [x] add scheduled task (with configurable interval) for trimming resourcechanges table
- [x] fix maxRecords check in `/changes` route to be `>=` instead of just `==`
- [x] add comment to `ApiTime.nowUTC`
