### ISSUE TITLE
Notification Framework Agbot Case

### ISSUE THREAD

**Issue by sf2ne** [open-horizon/exchange-api#311]
This is part of Epic 255
Agbot Case:
- [x] add `"orgList": ["", "", ""]` optional field in request body, that is a list of orgs that the agbot wants changes in
- [x] restructure the filters to more cleanly allow for agbot case
- [x] add agbot filter where if the agbot is a general agbot follow the user case filter and if the agbot is a "Super" agbot then it gets back all changes in the orgList that it sent in
- [x] allow for wildcard case ("" or "*") where if `orgList:  [""]` or `orgList: ["*"]` then the agbot gets back all changes from all orgs

Just a note: These are the resources that the agbot is going to care about: agbot msgs, node changes, node policy changes, bus pol changes, pattern changes, services changes, service policies changes

Additional work:
-  ~maybe add some more auth checks for users, maybe only admin users can call the exchange? Ask Bruce about this.~ --> bring this up in another issue with Doug if its still a problem
- [x] add some validation for `maxRecords` (set some cap of how high maxRecords can actually go)
- [x] set the `maxRecords` cap in config
