### ISSUE TITLE
Expand Current Exchange Tests

### ISSUE THREAD

**Issue by sf2ne** [open-horizon/exchange-api#320]
This is part of Epic 218

This issue is to write tests to cover some of the holes Jon found in his audit of the exchange tests.
These are the biggest areas of concern:
- [ ] ~Need more authentication tests (ibm cloud, ICP, OCP)~
- [x] Tests on the `/admin` routes to make sure non-admin or non-root users can't hit them
- [ ] ~When there's a PUT used a GET to validate~

There are more described in the documentation Jon wrote

**Comment by sf2ne** [comment]
`Need more authentication tests (ibm cloud, ICP, OCP)` moved to issue #335

**Comment by sf2ne** [comment]
`When there's a PUT used a GET to validate` moved to issue https://github.com/open-horizon/exchange-api/issues/338

**Comment by sf2ne** [comment]
Verified by @sf2ne
