### ISSUE TITLE
Fix Swagger Issues 

### ISSUE THREAD

**Issue by sf2ne** [open-horizon/exchange-api#344]
- [x] get rid of incorrect `Example Value | Schema` section (only leave `Request Body` and purple text json) (Sadiyah -- maybe Nathan if Sadiyah can't figure this out)
- [x] verify that the request body of all POST/PUT routes are actually accurate (Sadiyah)
- [x] verify response bodies of all GET routes (Sadiyah)
- [x] `/catalog/<orgid>/patterns` and `/catalog/<orgid>/services` routes not showing up in swagger, ~~also where did the get all node errors route go?~~ the `/search/nodes/error/all` route is actually on the swagger page (Sadiyah)
- [x] `POST ​/v1​/{orgid}​/search​/nodes​/service` should be `POST ​/v1​/orgs/{orgid}​/search​/nodes​/service` (Sadiyah)
- [x] Optional for this issue: Why does it say `default`?
- [x] Optional: Do we want the `Try It Out` button to work?

**Comment by JShelf** [comment]
* [ ] Clean up a few syntactic errors in swagger, so swagger validation can be passed. 
Errors can be found [here](https://ibm.box.com/s/dk25fesmqhuw476ip4v8ivfai0wtmhx7)
