### ISSUE TITLE
Prepare Translation

### ISSUE THREAD

**Issue by sf2ne** [open-horizon/exchange-api#348]
- [x] go through translation files and make sure they are up to date (Sadiyah)
- [x] submit in translation channel or email? (Sadiyah)
- [x] discuss testing, changing the language requires a redeployment -- how did they test for this last time? (Sadiyah)
