### ISSUE TITLE
Validation of `POST/PUT/PATCH` tests in Exchange `OrgsSuite`

### ISSUE THREAD

**Issue by sf2ne** [open-horizon/exchange-api#528]
## Description:

There are cases in the exchange unit tests where a `POST/PUT/PATCH` route test will not use a `GET` call or a database call to validate that the information was created and is consumable. For example:

```
  test("POST /orgs/"+orgid+" - create org") {
    // Try deleting it 1st, in case it is left over from previous test
    var response = Http(URL+"/"+orgid).method("delete").headers(ACCEPT).headers(ROOTAUTH).asString
    info("code: "+response.code+", response.body: "+response.body)
    assert(response.code === HttpCode.DELETED.intValue || response.code === HttpCode.NOT_FOUND.intValue)

    val input = PostPutOrgRequest(None, "My Org", "desc", None, None, None)
    response = Http(URL+"/"+orgid).postData(write(input)).method("post").headers(CONTENT).headers(ACCEPT).headers(ROOTAUTH).asString
    info("code: "+response.code+", response.body: "+response.body)
    assert(response.code === HttpCode.POST_OK.intValue)
  }
``` 
this test case should have a validation step added

```
  test("POST /orgs/"+orgid+" - create org") {
    // Try deleting it 1st, in case it is left over from previous test
    var response = Http(URL+"/"+orgid).method("delete").headers(ACCEPT).headers(ROOTAUTH).asString
    info("code: "+response.code+", response.body: "+response.body)
    assert(response.code === HttpCode.DELETED.intValue || response.code === HttpCode.NOT_FOUND.intValue)

    val input = PostPutOrgRequest(None, "My Org", "desc", None, None, None)
    response = Http(URL+"/"+orgid).postData(write(input)).method("post").headers(CONTENT).headers(ACCEPT).headers(ROOTAUTH).asString
    info("code: "+response.code+", response.body: "+response.body)
    assert(response.code === HttpCode.POST_OK.intValue)

    // Validation 
    response = Http(URL + "/" + orgid).method("get").headers(CONTENT).headers(ACCEPT).headers(HUBADMINAUTH).asString
    info("code: "+response.code)
    assert(response.code == HttpCode.OK.intValue)
    val orgsList = parse(response.body).extract[GetOrgsResponse]
    assert(orgsList.orgs.size == 1)
    assert(orgsList.orgs.contains(orgid))
  }
```

Alternatively the validation can be done with a database call as is shown in [these Test Cases written by](https://github.com/naphelps/exchange-api/blob/unit-test-updates/src/test/scala/com/horizon/exchangeapi/route/agbot/AgbotPutRouteTest.scala#L157) @naphelps 

## Tasks

- [ ] Isolate all the cases where a `POST/PUT/PATCH` test is done without any validation
- [ ] Add the validation through a `GET` call or a database call
- [ ] Verify all the tests are working and open issues for any non-working test cases

**Comment by MOLOCH-dev** [comment]
Hello, I'd like to contribute to this issue. Please assign me the same. Thank you!
