### ISSUE TITLE
Add JAAS/PAM auth framework to the exchange

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/exchange-api#76]
- [x] Modify exchange to use JAAS/PAM auth framework to authenticate users (#86)
- [x] use JAAS/PAM auth framework to authorize users (#86)
- [x] Cascading configuration system to provide defaults for backwards compatibility (#86)
- [x] Add a plugin for the above framework to authenticate IBM Cloud IAM user/pw or platform key as valid exchange users. (Their IBM Cloud account will be the exchange org.)

Part of https://github.ibm.com/Edge-Fabric/project-summary/issues/21

**Comment by bmpotter** [comment]
Moved the edge node service ID API keys feature to https://github.com/open-horizon/exchange-api/issues/78

**Comment by bmpotter** [comment]
Delayed to sprint 3 due to genesis work
